# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MAKE A WEB
email: info@makeaweb.com.au
author: Adam Koliński
description: > # this means to ignore newlines until "baseurl:"
    We build websites to help businesses thrive with a visual brand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://makeaweb.com.au" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
markdown: kramdown
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - /assets/node_modules/
  - /assets/images/src/
  - /assets/Gruntfile.js
  - /assets/package.json
  - /assets/package-lock.json
plugins_dir:
  - jemoji # https://gist.github.com/roachhd/1f029bd4b50b8a524f3c
permalink: /articles/:title
html_press:
  unquoted_attributes: false
  drop_empty_values: false
  strip_crlf: false
  js_minifier_options: false
incremental: true # Incremental regeneration, speeds up serve time
